//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ImageViewer.rc
//

#define IDR_MAINFRAME								200
#define IDD_IMAGEVIEWER_DIALOG						102
#define IDD_ABOUTBOX								103
#define ID_HELP_ABOUT								104
#define ID_FILE_EXIT								105
#define IDI_IMAGEVIEWER								107
#define IDI_SMALL									108
#define IDC_IMAGEVIEWER								109
#define ID_FILE_NEW									110
#define ID_FILE_OPEN								111
#define ID_FILE_NEXT								112
#define ID_FILE_PREVIOUS							113
#define ID_FILE_SETASDESKTOPBACKGROUND_CENTER		114
#define ID_FILE_SETASDESKTOPBACKGROUND_CROPTOFIT	115
#define ID_FILE_SETASDESKTOPBACKGROUND_KEEPASPECT	116
#define ID_FILE_SETASDESKTOPBACKGROUND_STRETCH		117
#define ID_FILE_SETASDESKTOPBACKGROUND_TILE			118
#define ID_FILE_OPENFILELOCATION					119
#define ID_FILE_ROTATECLOCKWISE						120
#define ID_FILE_ROTATECOUNTERCLOCKWISE				121
#define ID_FILE_COPY								122
#define ID_FILE_CUT									123
#define ID_FILE_DELETE								124
#define ID_FILE_DELETEPERMANENTLY					125
#define ID_FILE_PROPERTIES							126
#define ID_FILE_FULLSCREEN							127
#define ID_FILE_ACTUALSIZE							128
#define	ID_FILE_FITTOWINDOW							129
#define	ID_FILE_CLOSEALLWINDOWS						130
#define RETURNEDFROMCOMMONITEMDIALOGOPEN			131
#define IDC_HANDOPEN								132
#define IDC_HANDCLOSED								133
#define ID_FILE_FRAMEPREVIOUS						134
#define ID_FILE_FRAMENEXT							135
#define ID_FILE_TOGGLEBACKGROUNDCOLOR				136
#define RETURNEDFROMDELETEFILEWITHIFO				137
#define ID_FILE_ANIMATIONSTARTSTOP					138
#define ID_FILE_SORTBYDATEMODIFIED					139
#define ID_FILE_SORTBYNAME							140
#define ID_FILE_SORTBYSIZE							141
#define ID_FILE_FIRSTFILE							142
#define ID_FILE_LASTFILE							143
#define ID_FILE_SORTBYASCENDING						144
#define ID_FILE_SORTBYDESCENDING					145
#define ID_FILE_AUTOROTATE							146
#define ID_FILE_SCALETOWINDOW						147
//#define VS_VERSION_INFO								1 // For VERSIONINFO in .rc
#define IDC_MYICON									2

#ifndef IDC_STATIC
#define IDC_STATIC									-1
#endif

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					149
#define _APS_NEXT_RESOURCE_VALUE	201
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		148
#endif
#endif
